import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { alertService } from "../../services/alertService";
import { useClinicalAI } from "../../context/ClinicalAIContext";
import {
  X,
  HeartPulse,
  Thermometer,
  Droplets,
  Activity,
  BrainCircuit,
  BedDouble,
  User,
} from "lucide-react";

export default function AlertDrawer({
  open,
  alert,
  patient,
  onClose,
}) {
  const [loadingAction, setLoadingAction] = useState(null);

  /*
   * ClinicalAIContext manages alerts generated locally by AlertEngine.
   *
   * Example local alert IDs:
   * ICU-10251-spo2
   * ICU-10251-sbp
   * ICU-10251-hr-high
   * ICU-10251-temp-high
   * ICU-10251-lactate
   * ICU-10251-risk
   */
  const {
    acknowledgeAlert,
    resolveAlert,
    escalateAlert,
  } = useClinicalAI();

  /**
   * Detect whether the alert was generated locally
   * by AlertEngine.
   *
   * Backend alert IDs currently use formats such as:
   * TEMP-ICU-10264
   *
   * Local AlertEngine IDs use formats such as:
   * ICU-10251-spo2
   * ICU-10251-sbp
   */
  function isLocalAlert(alertId) {
    if (!alertId) {
      return false;
    }

    return (
      alertId.includes("-spo2") ||
      alertId.includes("-sbp") ||
      alertId.includes("-hr-high") ||
      alertId.includes("-hr-low") ||
      alertId.includes("-temp-high") ||
      alertId.includes("-temp-low") ||
      alertId.includes("-lactate") ||
      alertId.includes("-risk")
    );
  }

  /**
   * Resolve alert ID.
   *
   * Priority:
   * 1. alert.id
   * 2. alert.alert_id
   * 3. TEMP-{patient.id}
   */
  function getAlertId() {
    if (alert?.id) {
      return alert.id;
    }

    if (alert?.alert_id) {
      return alert.alert_id;
    }

    if (patient?.id) {
      return `TEMP-${patient.id}`;
    }

    return null;
  }

  /**
   * Execute alert action.
   *
   * Local alerts:
   * ClinicalAIContext
   *
   * Backend alerts:
   * alertService -> Railway API
   */
  async function handleAlertAction(action) {
    if (!alert) {
      window.alert("No alert selected.");
      return;
    }

    const alertId = getAlertId();

    if (!alertId) {
      console.error("Unable to determine alert ID.", {
        alert,
        patient,
      });

      window.alert("Unable to determine alert ID.");
      return;
    }

    const localAlert = isLocalAlert(alertId);

    console.log(`Executing alert action: ${action}`, {
      alertId,
      localAlert,
      alert,
      patientId: patient?.id,
    });

    setLoadingAction(action);

    try {
      let response;

      /*
       * ------------------------------------------------
       * LOCAL ALERT
       * ------------------------------------------------
       *
       * Alert was generated by AlertEngine.
       *
       * Do NOT send these IDs to the backend because
       * the backend does not have records such as:
       *
       * ICU-10251-spo2
       */
      if (localAlert) {
        switch (action) {
          case "acknowledge":
            await acknowledgeAlert(alertId);

            response = {
              success: true,
              message: "Alert acknowledged successfully.",
            };
            break;

          case "escalate":
            await escalateAlert(alertId);

            response = {
              success: true,
              message: "Alert escalated successfully.",
            };
            break;

          case "resolve":
            await resolveAlert(alertId);

            response = {
              success: true,
              message: "Alert resolved successfully.",
            };
            break;

          default:
            throw new Error(
              `Unsupported alert action: ${action}`
            );
        }
      }

      /*
       * ------------------------------------------------
       * BACKEND ALERT
       * ------------------------------------------------
       *
       * Alert exists in backend/PostgreSQL.
       *
       * Example:
       * TEMP-ICU-10264
       */
      else {
        switch (action) {
          case "acknowledge":
            response =
              await alertService.acknowledge(alertId);
            break;

          case "escalate":
            response =
              await alertService.escalate(alertId);
            break;

          case "resolve":
            response =
              await alertService.resolve(alertId);
            break;

          default:
            throw new Error(
              `Unsupported alert action: ${action}`
            );
        }
      }

      console.log(
        `Alert ${action} successful:`,
        response
      );

      const successMessage =
        response?.message ||
        `Alert action "${action}" completed successfully.`;

      window.alert(successMessage);

      onClose?.();
    } catch (error) {
      console.error(
        `Failed to ${action} alert:`,
        {
          alertId,
          localAlert,
          status: error?.response?.status,
          data: error?.response?.data,
          message: error?.message,
          error,
        }
      );

      const backendMessage =
        error?.response?.data?.detail ||
        error?.response?.data?.message;

      window.alert(
        backendMessage ||
          `Failed to ${action} alert.`
      );
    } finally {
      setLoadingAction(null);
    }
  }

  function handleAcknowledge() {
    return handleAlertAction("acknowledge");
  }

  function handleEscalate() {
    return handleAlertAction("escalate");
  }

  function handleResolve() {
    return handleAlertAction("resolve");
  }

  const isLoading = loadingAction !== null;

  return (
    <AnimatePresence>
      {open && (
        <>
          {/* Backdrop */}

          <motion.div
            className="fixed inset-0 z-40 bg-black/40"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={isLoading ? undefined : onClose}
          />

          {/* Drawer */}

          <motion.div
            initial={{ x: 500 }}
            animate={{ x: 0 }}
            exit={{ x: 500 }}
            transition={{ duration: 0.3 }}
            className="fixed right-0 top-0 z-50 h-screen w-[480px] overflow-y-auto border-l bg-white shadow-2xl"
          >
            {/* Header */}

            <div className="flex items-center justify-between border-b p-6">
              <div>
                <h2 className="text-2xl font-bold">
                  Clinical Alert
                </h2>

                <p className="text-slate-500">
                  AI Clinical Details
                </p>
              </div>

              <button
                onClick={onClose}
                disabled={isLoading}
                className="rounded-xl p-2 hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-50"
              >
                <X />
              </button>
            </div>

            <div className="space-y-6 p-6">
              {/* Patient */}

              <div className="rounded-2xl bg-cyan-50 p-5">
                <div className="flex items-center gap-3">
                  <User className="text-cyan-600" />

                  <div>
                    <h3 className="text-xl font-bold">
                      {patient?.name ||
                        alert?.patient_name ||
                        "Unknown Patient"}
                    </h3>

                    <p className="text-slate-500">
                      {patient?.id ||
                        alert?.patient_id ||
                        "N/A"}
                    </p>
                  </div>
                </div>
              </div>

              {/* Alert */}

              <div className="rounded-2xl border p-5">
                <h3 className="font-bold">
                  Current Alert
                </h3>

                <p className="mt-3 text-lg">
                  {alert?.title ||
                    alert?.type ||
                    "Clinical Alert"}
                </p>

                <p className="mt-2 text-slate-600">
                  {alert?.message ||
                    "No additional alert details available."}
                </p>
              </div>

              {/* Bed / Risk */}

              <div className="grid grid-cols-2 gap-4">
                <div className="rounded-xl border p-4">
                  <BedDouble className="mb-2 text-cyan-600" />

                  <p className="text-sm text-slate-500">
                    ICU Bed
                  </p>

                  <h3 className="text-xl font-bold">
                    {patient?.bed ||
                      alert?.bed ||
                      "N/A"}
                  </h3>
                </div>

                <div className="rounded-xl border p-4">
                  <BrainCircuit className="mb-2 text-violet-600" />

                  <p className="text-sm text-slate-500">
                    AI Risk
                  </p>

                  <h3 className="text-xl font-bold">
                    {typeof patient?.risk_score ===
                    "number"
                      ? `${(
                          patient.risk_score * 100
                        ).toFixed(0)}%`
                      : "N/A"}
                  </h3>
                </div>
              </div>

              {/* Vitals */}

              <div>
                <h3 className="mb-4 text-xl font-bold">
                  Live Vitals
                </h3>

                <div className="grid grid-cols-2 gap-4">
                  <VitalCard
                    icon={<HeartPulse />}
                    label="Heart Rate"
                    value={
                      patient?.heart_rate != null
                        ? `${patient.heart_rate} BPM`
                        : "N/A"
                    }
                  />

                  <VitalCard
                    icon={<Activity />}
                    label="Blood Pressure"
                    value={
                      patient?.systolic_bp != null &&
                      patient?.diastolic_bp != null
                        ? `${patient.systolic_bp}/${patient.diastolic_bp}`
                        : "N/A"
                    }
                  />

                  <VitalCard
                    icon={<Droplets />}
                    label="SpO₂"
                    value={
                      patient?.spo2 != null
                        ? `${patient.spo2}%`
                        : "N/A"
                    }
                  />

                  <VitalCard
                    icon={<Thermometer />}
                    label="Temperature"
                    value={
                      patient?.temperature != null
                        ? `${patient.temperature} °C`
                        : "N/A"
                    }
                  />
                </div>
              </div>

              {/* AI Recommendation */}

              <div className="rounded-2xl bg-violet-50 p-5">
                <h3 className="font-bold">
                  AI Recommendation
                </h3>

                <ul className="mt-4 list-disc space-y-2 pl-5 text-slate-700">
                  <li>Start Sepsis Protocol</li>
                  <li>Repeat Lactate Test</li>
                  <li>Obtain Blood Cultures</li>
                  <li>Notify ICU Physician</li>
                </ul>
              </div>

              {/* Footer */}

              <div className="flex flex-col gap-3">
                <button
                  onClick={handleAcknowledge}
                  disabled={isLoading}
                  className="rounded-xl bg-cyan-600 py-3 font-semibold text-white hover:bg-cyan-700 disabled:cursor-not-allowed disabled:opacity-50"
                >
                  {loadingAction === "acknowledge"
                    ? "Processing..."
                    : "✓ Acknowledge"}
                </button>

                <button
                  onClick={handleEscalate}
                  disabled={isLoading}
                  className="rounded-xl bg-red-600 py-3 font-semibold text-white hover:bg-red-700 disabled:cursor-not-allowed disabled:opacity-50"
                >
                  {loadingAction === "escalate"
                    ? "Processing..."
                    : "🚨 Escalate"}
                </button>

                <button
                  onClick={handleResolve}
                  disabled={isLoading}
                  className="rounded-xl bg-emerald-600 py-3 font-semibold text-white hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-50"
                >
                  {loadingAction === "resolve"
                    ? "Processing..."
                    : "✔ Resolve"}
                </button>
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}

function VitalCard({
  icon,
  label,
  value,
}) {
  return (
    <div className="rounded-xl border p-4">
      <div className="mb-3 text-cyan-600">
        {icon}
      </div>

      <p className="text-sm text-slate-500">
        {label}
      </p>

      <h3 className="text-xl font-bold">
        {value}
      </h3>
    </div>
  );
}