"""
app/vector_db/chroma_service.py

ChromaDB Vector Database Service — Phase 14.1.

Responsibilities:
  - Initialize a persistent ChromaDB client using config parameters.
  - Create and manage vector collections.
  - Expose operational APIs: health check, collection statistics.
  - Expose CRUD APIs: add documents, query documents, delete documents.
  - Support both built-in embedding functions and pre-computed embeddings
    (such as those generated by app.rag.embedding_service).

Design:
  - Singleton architecture: expose a global `chroma_service` instance.
  - Thread-safe operations using RLock.
  - Robust exception handling to prevent server crashes on database errors.
"""

from __future__ import annotations

import logging
import threading
from typing import Any, Dict, List, Optional, Union

import chromadb
from chromadb.api.types import EmbeddingFunction

from app.vector_db.config import CHROMA_DB_DIR, CHROMA_COLLECTION_NAME

logger = logging.getLogger(__name__)


class ChromaService:
    """
    Enterprise facade for interacting with ChromaDB.

    Thread-safe singleton wrapping PersistentClient.
    """

    def __init__(self, persist_dir: str = CHROMA_DB_DIR) -> None:
        self._lock = threading.RLock()
        self._persist_dir = persist_dir
        self._client: Optional[chromadb.PersistentClient] = None
        self._collection_name = CHROMA_COLLECTION_NAME

        logger.info("[ChromaService] Initializing with storage path: %s", self._persist_dir)
        try:
            self._client = chromadb.PersistentClient(path=self._persist_dir)
            logger.info("[ChromaService] Persistent client successfully initialized.")
        except Exception as e:
            logger.error("[ChromaService] Failed to initialize persistent client: %s", e)
            raise RuntimeError(f"ChromaDB initialization failed: {e}") from e

    # ------------------------------------------------------------------
    # Collection Management
    # ------------------------------------------------------------------

    def get_or_create_collection(
        self,
        name: Optional[str] = None,
        embedding_function: Optional[EmbeddingFunction] = None,
    ) -> Any:
        """
        Retrieve an existing collection or create a new one.

        Parameters
        ----------
        name : Optional[str]
            Name of the collection. Defaults to CHROMA_COLLECTION_NAME config.
        embedding_function : Optional[EmbeddingFunction]
            Custom embedding function. If None, Chroma's default is used.
        """
        col_name = name or self._collection_name
        with self._lock:
            if not self._client:
                raise RuntimeError("ChromaDB client is not initialized.")
            try:
                collection = self._client.get_or_create_collection(
                    name=col_name,
                    embedding_function=embedding_function,
                )
                logger.info("[ChromaService] Retrieved/Created collection: %s", col_name)
                return collection
            except Exception as e:
                logger.error("[ChromaService] Failed to get/create collection '%s': %s", col_name, e)
                raise

    # ------------------------------------------------------------------
    # CRUD Operations
    # ------------------------------------------------------------------

    def add_documents(
        self,
        ids: List[str],
        documents: List[str],
        metadatas: Optional[List[Dict[str, Any]]] = None,
        embeddings: Optional[List[List[float]]] = None,
        collection_name: Optional[str] = None,
    ) -> bool:
        """
        Insert or update documents into the collection.

        Parameters
        ----------
        ids : List[str]
            List of unique document identifiers.
        documents : List[str]
            List of document content strings.
        metadatas : Optional[List[Dict[str, Any]]]
            List of metadata dicts parallel to documents.
        embeddings : Optional[List[List[float]]]
            List of pre-computed embedding vectors parallel to documents.
        collection_name : Optional[str]
            Target collection. Defaults to default collection.
        """
        if not ids or not documents:
            logger.warning("[ChromaService] add_documents called with empty payload.")
            return False

        with self._lock:
            try:
                collection = self.get_or_create_collection(collection_name)
                collection.upsert(
                    ids=ids,
                    documents=documents,
                    metadatas=metadatas,
                    embeddings=embeddings,
                )
                logger.info("[ChromaService] Successfully added %d documents.", len(ids))
                return True
            except Exception as e:
                logger.error("[ChromaService] Error adding documents: %s", e)
                return False

    def query_documents(
        self,
        query_texts: Optional[Union[str, List[str]]] = None,
        query_embeddings: Optional[Union[List[float], List[List[float]]]] = None,
        n_results: int = 5,
        where: Optional[Dict[str, Any]] = None,
        collection_name: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Search for similar documents using query texts or embedding vectors.

        Parameters
        ----------
        query_texts : Optional[Union[str, List[str]]]
            Raw search text(s).
        query_embeddings : Optional[Union[List[float], List[List[float]]]]
            Pre-computed query vector(s) (e.g., from bge-small-en-v1.5).
        n_results : int
            Max number of similar documents to return.
        where : Optional[Dict[str, Any]]
            Metadata filter dict (e.g. {"source": "nice"}).
        collection_name : Optional[str]
            Target collection name.
        """
        if not query_texts and not query_embeddings:
            logger.warning("[ChromaService] query_documents called without query_texts or query_embeddings.")
            return {"ids": [], "distances": [], "metadatas": [], "documents": []}

        # Normalize query input formats for Chroma API
        q_texts = [query_texts] if isinstance(query_texts, str) else query_texts
        q_embs = query_embeddings
        if q_embs is not None and isinstance(q_embs[0], float):
            q_embs = [q_embs]  # type: ignore

        with self._lock:
            try:
                collection = self.get_or_create_collection(collection_name)
                results = collection.query(
                    query_texts=q_texts,
                    query_embeddings=q_embs,
                    n_results=n_results,
                    where=where,
                )
                return results
            except Exception as e:
                logger.error("[ChromaService] Error querying documents: %s", e)
                return {"ids": [], "distances": [], "metadatas": [], "documents": []}

    def delete_documents(
        self,
        ids: Optional[List[str]] = None,
        where: Optional[Dict[str, Any]] = None,
        collection_name: Optional[str] = None,
    ) -> bool:
        """
        Delete documents from the collection by IDs and/or metadata filter.

        Parameters
        ----------
        ids : Optional[List[str]]
        where : Optional[Dict[str, Any]]
        collection_name : Optional[str]
        """
        if ids is None and where is None:
            logger.warning("[ChromaService] delete_documents called without IDs or where filter.")
            return False

        with self._lock:
            try:
                collection = self.get_or_create_collection(collection_name)
                collection.delete(ids=ids, where=where)
                logger.info("[ChromaService] Successfully deleted documents matching parameters.")
                return True
            except Exception as e:
                logger.error("[ChromaService] Error deleting documents: %s", e)
                return False

    def get_all_documents(
        self,
        collection_name: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Retrieve all document IDs, metadatas, and content from the collection.
        """
        with self._lock:
            try:
                collection = self.get_or_create_collection(collection_name)
                # get() without query params returns all records (metadata, document texts, but excluding embeddings by default)
                results = collection.get()
                return results
            except Exception as e:
                logger.error("[ChromaService] Error retrieving all documents: %s", e)
                return {"ids": [], "metadatas": [], "documents": []}

    # ------------------------------------------------------------------
    # System Diagnostics
    # ------------------------------------------------------------------

    def health_check(self) -> bool:
        """
        Verify that the client connection is healthy.
        Returns True if heartbeat is received, False otherwise.
        """
        if not self._client:
            return False
        try:
            hb = self._client.heartbeat()
            return isinstance(hb, int)
        except Exception as e:
            logger.warning("[ChromaService] Health check heartbeat failed: %s", e)
            return False

    def get_stats(self, collection_name: Optional[str] = None) -> Dict[str, Any]:
        """
        Gather collection metrics.

        Returns
        -------
        Dict with keys: collection_name, document_count, storage_dir, healthy.
        """
        col_name = collection_name or self._collection_name
        count = 0
        healthy = self.health_check()
        if healthy:
            try:
                collection = self.get_or_create_collection(col_name)
                count = collection.count()
            except Exception:
                pass

        return {
            "collection_name": col_name,
            "document_count":  count,
            "storage_dir":      self._persist_dir,
            "healthy":          healthy,
        }


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------
chroma_service = ChromaService()
