"""create vital signs table

Revision ID: 1bdad71ccaeb
Revises: 6ba13ac43bc2
Create Date: 2026-07-07 15:34:13.711294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bdad71ccaeb'
down_revision: Union[str, Sequence[str], None] = '6ba13ac43bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vital_signs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admission_id', sa.String(length=36), nullable=False),
    sa.Column('heart_rate', sa.Float(), nullable=False),
    sa.Column('systolic_bp', sa.Float(), nullable=False),
    sa.Column('diastolic_bp', sa.Float(), nullable=False),
    sa.Column('respiratory_rate', sa.Float(), nullable=False),
    sa.Column('spo2', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('glasgow_coma_scale', sa.Integer(), nullable=False),
    sa.Column('urine_output_ml', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vital_signs_admission_id'), 'vital_signs', ['admission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vital_signs_admission_id'), table_name='vital_signs')
    op.drop_table('vital_signs')
    # ### end Alembic commands ###
