"""create admissions table

Revision ID: b8c2bd5e3435
Revises: 09158d41f49a
Create Date: 2026-07-07 14:28:41.372899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c2bd5e3435'
down_revision: Union[str, Sequence[str], None] = '09158d41f49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('admission_number', sa.String(length=30), nullable=False),
    sa.Column('diagnosis', sa.String(length=300), nullable=False),
    sa.Column('doctor_name', sa.String(length=100), nullable=False),
    sa.Column('ward', sa.String(length=50), nullable=False),
    sa.Column('bed_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admitted_at', sa.DateTime(), nullable=False),
    sa.Column('discharged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admissions')
    # ### end Alembic commands ###
