"""
Pydantic schemas for Clinical Report Generator.
"""

from pydantic import BaseModel, Field
from typing import Dict, Any

class ClinicalReportRequest(BaseModel):
    """
    Validation schema for creating a new clinical report.
    """
    patient_id: str = Field(..., description="Unique ID of the patient", example="ICU-10248")
    report_type: str = Field(..., description="Type of report to generate (ICU Progress Note, Daily Clinical Summary, Shift Handover, Discharge Summary)", example="ICU Progress Note")

class ClinicalReportResponse(BaseModel):
    """
    Validation schema for report output.
    """
    report_id: str = Field(..., description="Unique report ID generated by system")
    patient_id: str = Field(..., description="ID of the patient")
    patient_name: str = Field(..., description="Full name of the patient")
    report_type: str = Field(..., description="Selected report type format")
    created_at: str = Field(..., description="Timestamp of report generation")
    content: Dict[str, Any] = Field(..., description="Full structured JSON report context")
